# Generated by Django 4.1.3 on 2022-11-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='Dish_item',
        ),
    ]
